apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dta1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-dta1@sha256:fa89bee14ba9124011c37cd4bfe9eb13ae752b675e7e61c4225fd4091d105f7c
        name: my-nodejs
        resources: {}
status: {}
